name:                glados
version:             0.1.0.0
github:              "MartinFillon/gladdos"
license:             BSD-3-Clause
author:              "Martin Fillon"
maintainer:          "martin.fillon@hotmail.com"
copyright:           "2024 Martin Fillon"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gladdos#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec == 9.5.0
- text
- parser-combinators
- sexpresso

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  glados-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados

tests:
  glados-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fhpc
    dependencies:
    - glados
    - hspec
