name: Conventional Commits

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  build:
    name: Conventional Commits
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@v1.2.0
