name: "glados"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      - dev

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-FUN-500-PAR-5-2-glados-martin.fillon.git"

jobs:
  build:
    runs-on: self-hosted
    name: Building stack
    strategy:
      matrix:
        projects:
          - maryl
          - lisp

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build ${{ matrix.projects }}
        run: |
          cd ${{ matrix.projects }}
          stack build --allow-different-user
          stack test --allow-different-user

  push_to_mirror:
    needs: [build]
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')}}
    name: "pushes all files to mirror specified"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.KEY }}
