name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: self-hosted
    name: Building stack
    strategy:
      matrix:
        projects:
          - maryl
          - lisp

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build ${{ matrix.projects }}
        run: |
          cd ${{ matrix.projects }}
          make
          mv glados ../glados-${{ matrix.projects }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            glados-lisp
            glados-maryl
