name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: self-hosted
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: sudo make re && mv lisp/glados glados-lisp && mv maryl/glados glados-maryl

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            glados-lisp
            glados-maryl
