name: "glados"

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  make_tests_run:
    runs-on: self-hosted
    name: run tests
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check tests
        run: |
          sudo stack test --allow-different-user
